const Homeproduct=[
    {
        id:1,
        Name:'product1',
        price:'26',
        image: 'image/p1.webp',
        cat:'tv',
        type:'new',
    },
    {
        id:2,
        Name:'product1',
        price:'260',
        image: 'image/p2.webp',
        cat:'laptop',
        type:'new',
    },
    {
        id:3,
        Name:'product1',
        price:'206',
        image: 'image/p3.webp',
        cat:'watch',
        type:'featured',
    },
    {
        id:4,
        Name:'product1',
        price:'96',
        image: 'image/p4.webp',
        cat:'speaker',
        type:'featured',
    },
    {
        id:5,
        Name:'product1',
        price:'265',
        image: 'image/p5.webp',
        cat:'camera',
        type:'featured',
    },
    {
        id:6,
        Name:'product1',
        price:'60',
        image: 'image/p8.webp',
        cat:'speaker',
        type:'new',
    },
    {
        id:7,
        Name:'product1',
        price:'126',
        image: 'image/p7.webp',
        cat:'electronic',
        type:'top',
    },
    {
        id:8,
        Name:'product1',
        price:'960',
        image: 'image/p10.jpg',
        cat:'headphones',
        type:'top',
    },
    {
        id:9,
        Name:'product1',
        price:'1060',
        image: 'image/p9.jpg',
        cat:'laptop',
        type:'top',
    },
    {
        id:10,
        Name:'product1',
        price:'60',
        image: 'image/p12.jpg',
        cat:'speaker',
        type:'top',
    },
    {
        id:11,
        Name:'product1',
        price:'160',
        image: 'image/p11.jpg',
        cat:'mobile',
        type:'top',
    },
    {
        id:12,
        Name:'product1',
        price:'55',
        image: 'image/p7.webp',
        cat:'electronic',
        type:'top',
    }
]

export default Homeproduct